name: Build YTDown APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Sistem paketleri
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libtinfo5 cmake libffi-dev libssl-dev build-essential ccache

      - name: Buildozer kur
        run: |
          pip install buildozer cython==0.29.33

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.buildozer
            ~/.gradle
          key: buildozer-${{ hashFiles('buildozer.spec') }}

      - name: APK Build
        run: buildozer -v android debug

      - name: APK Kaydet
        uses: actions/upload-artifact@v4
        with:
          name: YTDown-APK
          path: bin/*.apk
          retention-days: 30
